### ISSUE TITLE
TurboDiff: Support jsonPatch output

### ISSUE THREAD

**Issue by sarendipitee** [ZxBing0066/zlib#3]
Big fan of turbo diff. It is definitely the quickest algo I've found so far!

But applying the changes is a bit cumbersome because of the output format.

Would you be open to supporting the jsonPatch format for turboDiff? https://jsonpatch.com/

There are already numerous implementations for this format so it would promote code reuse without having to first map the output of each diff to this format.

**Comment by ZxBing0066** [comment]
A bit late to deal with this, I added a jsonPatch formatter to meet your requirement, you can upgrade to `1.1.0` and try:

```ts
import diff from "turbo-diff";
import jsonPatchFormatter from "turbo-diff/esm/formatter/jsonPatch";

console.log(jsonPatchFormatter(diff(oldDeepObj, newDeepObj)));
// [{op: "add", path: "/newKey", value: "new content"}]
```

You can also regard this demo: https://codesandbox.io/s/playground-turbo-diff-forked-qhdk52?file=/src/index.js

------

This is a straightforward solution but will slow the performance (10%-30%). A better solution is to use a compiler to export different code for different formats. However, it's a bit complex and I don't have enough time to do that. If you'd like, please feel free to send a PR.
